name       : bazel
version    : 3.3.1
release    : 9
source     :
    - https://github.com/bazelbuild/bazel/releases/download/3.3.1/bazel-3.3.1-dist.zip : e0f1f43c65c4e0a38522b37e81f6129d8a1f7cd3d8884847be306544a7492747
license    : Apache-2.0
component  : programming.tools
summary    : A fast, scalable, multi-language and extensible build system
description: |
    A fast, scalable, multi-language and extensible build system
debug      : no
strip      : no
builddeps  :
    - openjdk-11
rundeps    :
    - openjdk-11
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-11
build      : |
    env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash compile.sh
    $workdir/scripts/generate_bash_completion.sh \
        --bazel=$workdir/output/bazel --output=$workdir/output/bazel.bash \
        --prepend=$workdir/scripts/bazel-complete-header.bash \
        --prepend=$workdir/scripts/bazel-complete-template.bash
install    : |
    install -Dm00755 output/bazel -t $installdir/usr/share/bazel
    install -Dm00755 $pkgfiles/bazel.sh $installdir/usr/bin/bazel

    install -Dm00644 output/bazel.bash $installdir/usr/share/bash-completion/completions/bazel
    install -Dm00644 $workdir/scripts/zsh_completion/_bazel $installdir/usr/share/zsh/site-functions/_bazel
    install -Dm00644 $workdir/scripts/fish/completions/bazel.fish $installdir/usr/share/fish/vendor_completions.d/bazel.fish
