name       : bazel
version    : 0.16.0
release    : 1
source     :
    - https://github.com/bazelbuild/bazel/releases/download/0.16.0/bazel-0.16.0-dist.zip : c730593916ef0ba62f3d113cc3a268e45f7e8039daf7b767c8641b6999bd49b1
license    : Apache-2.0
component  : programming.tools
summary    : A fast, scalable, multi-language and extensible build system
description: |
    A fast, scalable, multi-language and extensible build system
strip      : no
builddeps  :
    - openjdk-8
build      : |
    bash compile.sh
install:
    install -Dm00755 output/bazel $installdir/usr/bin/bazel
