name       : bazel
version    : 0.25.2
release    : 5
source     :
    - https://github.com/bazelbuild/bazel/releases/download/0.25.2/bazel-0.25.2-dist.zip : 7456032199852c043e6c5b3e4c71dd8089c1158f72ec554e6ec1c77007f0ab51
license    : Apache-2.0
component  : programming.tools
summary    : A fast, scalable, multi-language and extensible build system
description: |
    A fast, scalable, multi-language and extensible build system
debug      : no
strip      : no
networking : yes
builddeps  :
    - openjdk-8
rundeps    :
    - openjdk-8
build      : |
    bash compile.sh
    output/bazel build //scripts:bazel-complete.bash
    output/bazel shutdown
install    : |
    install -Dm00755 output/bazel $installdir/usr/bin/bazel
    install -Dm00644 $workdir/bazel-bin/scripts/bazel-complete.bash $installdir/usr/share/bash-completion/completions/bazel
    install -Dm00644 $workdir/scripts/zsh_completion/_bazel $installdir/usr/share/zsh/site-functions/_bazel
