name       : bazel
version    : 5.1.1
release    : 17
source     :
    - https://github.com/bazelbuild/bazel/releases/download/5.1.1/bazel-5.1.1-dist.zip : 7f5d3bc1d344692b2400f3765fd4b5c0b636eb4e7a8a7b17923095c7b56a4f78
license    : Apache-2.0
component  : programming.tools
homepage   : https://bazel.build/
summary    : A fast, scalable, multi-language and extensible build system
description: |
    Bazel is an open-source build and test tool similar to Make, Maven, and Gradle. It uses a human-readable, high-level build language. Bazel supports projects in multiple languages and builds outputs for multiple platforms. Bazel supports large codebases across multiple repositories, and large numbers of users.
networking : yes
debug      : no
strip      : no
builddeps  :
    - openjdk-11
rundeps    :
    - openjdk-11
build      : |
    export JAVA_HOME=/usr/lib64/openjdk-11
    env EMBED_LABEL=$version EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash compile.sh
    $workdir/scripts/generate_bash_completion.sh \
        --bazel=$workdir/output/bazel --output=$workdir/output/bazel.bash \
        --prepend=$workdir/scripts/bazel-complete-header.bash \
        --prepend=$workdir/scripts/bazel-complete-template.bash
    ./output/bazel build scripts:bazel-complete.bash
    ./output/bazel build scripts:fish_completion
    ./output/bazel shutdown
install    : |
    install -Dm00755 output/bazel -t $installdir/usr/share/bazel
    install -Dm00755 $pkgfiles/bazel.sh $installdir/usr/bin/bazel

    install -Dm00644 output/bazel.bash $installdir/usr/share/bash-completion/completions/bazel
    install -Dm00644 $workdir/scripts/zsh_completion/_bazel $installdir/usr/share/zsh/site-functions/_bazel
    install -Dm00644 $workdir/bazel-bin/scripts/bazel.fish $installdir/usr/share/fish/vendor_completions.d/bazel.fish
